# Generated by Django 5.0.6 on 2024-07-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_project', '0004_userprofile_telegram_setup_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='telegram_chat_id',
            new_name='telegram_id',
        ),
    ]
