# Generated by Django 5.0.6 on 2024-07-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_project', '0005_rename_telegram_chat_id_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='show_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='KnownEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_downloaded', models.BooleanField(default=False)),
                ('season', models.IntegerField(default=0)),
                ('episode', models.IntegerField(default=0)),
                ('torrent_hash', models.CharField(blank=True, default='', max_length=255)),
                ('last_check', models.DateTimeField(auto_now_add=True)),
                ('Link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='jwt_project.link')),
            ],
        ),
    ]
