# Generated by Django 5.0.6 on 2024-07-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_project', '0006_link_show_name_alter_userprofile_telegram_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knownepisode',
            old_name='Link',
            new_name='link',
        ),
    ]
